### ISSUE TITLE
Bug: exception last card of filtered deck

### ISSUE THREAD

**Issue by NSBum** [xquercus/change-order-of-review-cards#5]
Anki 2.1.44, macOS 10.15.7

### Steps to reproduce

1. Enable _Change Order of Review Cards in Regular Decks⁩_ add-on
2. Create a filtered deck
3. Review deck. 
4. Note last card causes exception listed below:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-08 09:29:50
Add-ons possibly involved: ⁨Change Order of Review Cards in Regular Decks⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "aqt/reviewer.py", line 337, in _onAnswerButton
  File "aqt/reviewer.py", line 274, in _answerCard
  File "aqt/reviewer.py", line 116, in nextCard
  File "anki/schedv2.py", line 101, in getCard
  File "anki/schedv2.py", line 131, in _getCard
  File "anki/schedv2.py", line 442, in _getRevCard
  File "/Users/alan/Library/Application Support/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  File "/Users/alan/Library/Application Support/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  File "/Users/alan/Library/Application Support/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  [Previous line repeated 977 more times]
  File "/Users/alan/Library/Application Support/Anki2/addons21/3731265543/__init__.py", line 62, in _v2_fillRev
    lim = min(self.queueLimit, self._currentRevLimit())
  File "anki/schedv2.py", line 390, in _currentRevLimit
  File "anki/decks.py", line 411, in selected
  File "anki/config.py", line 51, in __getitem__
  File "anki/config.py", line 37, in get_immutable
  File "anki/_backend/generated.py", line 662, in get_config_json
  File "anki/_backend/__init__.py", line 99, in _run_command
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by shouya** [comment]
The bug seems not just limit to filtered decks. I have a regular deck and occasionally see the same error on the last card.

Note, it's last card on the "review" queue. It can happen when there are still more cards from the "new" and "learning" queue.

Here is the log with version information:

``` text
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Linux-6.1.0-7-amd64-x86_64-with-glibc2.36
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-08 16:33:19
Add-ons possibly involved: ⁨Change Order of Review Cards in Regular Decks⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 532, in _onAnswerButton
  File "aqt.reviewer", line 457, in _answerCard
  File "aqt.reviewer", line 464, in _after_answering
  File "aqt.reviewer", line 227, in nextCard
  File "aqt.reviewer", line 255, in _get_next_v1_v2_card
  File "anki.scheduler.v2", line 105, in getCard
  File "anki.scheduler.v2", line 134, in _getCard
  File "anki.scheduler.v2", line 443, in _getRevCard
  File "/home/shou/.local/share/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  File "/home/shou/.local/share/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  File "/home/shou/.local/share/Anki2/addons21/3731265543/__init__.py", line 84, in _v2_fillRev
    return self._fillRev()
  [Previous line repeated 971 more times]
  File "/home/shou/.local/share/Anki2/addons21/3731265543/__init__.py", line 62, in _v2_fillRev
    lim = min(self.queueLimit, self._currentRevLimit())
  File "anki.scheduler.v2", line 392, in _currentRevLimit
  File "anki.decks", line 414, in get_current_id
  File "anki._backend_generated", line 588, in get_current_deck
  File "google.protobuf.message", line 202, in ParseFromString
  File "google.protobuf.internal.python_message", line 1128, in MergeFromString
  File "google.protobuf.internal.python_message", line 1195, in InternalParse
  File "google.protobuf.internal.decoder", line 719, in DecodeField
  File "google.protobuf.internal.python_message", line 454, in MakeSubMessageDefault
  File "google.protobuf.internal.python_message", line 514, in init
  File "google.protobuf.internal.python_message", line 1498, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object

```
